# Generated by Django 5.0.7 on 2024-08-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='default_name', max_length=255),
            preserve_default=False,
        ),
    ]
