# Generated by Django 5.0.7 on 2024-08-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='logged_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
